version: 2
updates:
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
  assignees:
  - rjeczalik
- package-ecosystem: gomod
  directory: /
  schedule:
    interval: weekly
  assignees:
  - rjeczalik
