name: Go

on:
  push:
    branches:
    - "main"
  pull_request:
    branches:
    - "main"

jobs:
  lint:
    runs-on: ubuntu-latest
    name: lint
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "stable"
      - run: go build -v ./...
      - uses: scylladb/goimports-action@v1.0.2
        with:
          goimports-path: './'
      - uses: scylladb/gofmt-action@v1.0.5
        with:
          gofmt-path: './'
          gofmt-flags: '-l -d'
      - uses: golangci/golangci-lint-action@v3
        with:
          version: v1.56.2
      - run: go test -v -race ./...
  test-build:
    strategy:
      matrix:
        go: [ "stable" ]
        os: [ macos-latest, windows-latest, ubuntu-latest ]
    name: test-build
    needs: lint
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - run: go build -v ./...
      - run: go test -v -race ./...
